### ISSUE TITLE
Update Database Structure to Allow More Granular Access Control

### ISSUE THREAD

**Issue by dfreseInnovate** [Innovate-Inc/Frederick-CO#62]
Create 3 feature datasets and move the following feature class into the dataset:

 

**Planning – Feature dataset**

- Unbuilt_Dwelling – feature class

 

**Engineering – Feature dataset**

-   Pavement_Management

-   Meters

-   Watervalves

-   Waterlines

-   Raw Water Values

-   Raw Water Lines

-   Town of Frederick Service Area

-   Town of Frederick Future Service Area

-   All the stormwater feature classes

**Public Works - Feature Dataset**

-    Hydrants

**Comment by tvlombardi** [comment]
![image](https://user-images.githubusercontent.com/49164779/154708760-5ae3e452-1f5d-4b61-ac82-97e3e98d724d.png)
