### ISSUE TITLE
Lead Service Line Update 

### ISSUE THREAD

**Issue by dfreseInnovate** [Innovate-Inc/Frederick-CO#96]
Can we swap out the hosted feature layer for one published from enterprise geodatabase?

- [x] Review how hosted feature layer is used in Solution maps.  Can we use a feature service referencing data in SQL Server instead of a hosted layer? Can we use AGOL Assistant to swap out data sources?
- [x] Develop LOE - sent to Cindy describing the process.

**Comment by ckamigaki** [comment]
We implemented Leadline into our water meter dataset.  Can close out, no further action is needed.
